pool:
  vmImage: Ubuntu-16.04

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 10

  - script: yarn install --frozen-lockfile
    displayName: Install dependencies

  - script: |
      yarn lint
      yarn prettier:check
      yarn copy:paste:detector
    displayName: Check code

  - task: PublishPipelineArtifact@0
    displayName: Publish jscpd HTML report
    condition: failed()
    inputs:
      artifactName: 'CopyPasteDetectorReport'
      targetPath: 'target/jscpd-report.html'

  - script: yarn compile
    displayName: Compile source code

  - script: npm run test:unit:ci
    displayName: Run unit tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'target/test-results.xml'
      testRunTitle: Test results for JavaScript
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/target/coverage/cobertura-coverage.xml
      reportDirectory: $(System.DefaultWorkingDirectory)/target/coverage

  - script: yarn now -t $NOW_TOKEN -e GITLAB_SECRET_TOKEN -e IFTTT_KEY -e MONGO_URI -e SENTRY_DSN --target production
    displayName: Production deploy to ZEIT Now
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      NOW_TOKEN: $(nowKey)
      GITLAB_SECRET_TOKEN: $(gitlabSecret)
      IFTTT_KEY: $(iftttKey)
      MONGO_URI: $(mongoUri)
      SENTRY_DSN: $(sentryDSN)
