version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4567-4597:4567-4597
      - 8080:8080
    environment:
      - SERVICES=apigateway,lambda,dynamodb,sns
      - DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
