version: '3.7'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4567-4597:4567-4597
    environment:
      - SERVICES=apigateway,lambda,dynamodb,sns
      - DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - START_WEB=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
