version: '3.6'

services:
  redis:
    image: redis:6.0.5-alpine
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./target/data:/data
    restart: unless-stopped
  cibulb:
    container_name: cibulb
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped
