name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.0.5-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Check source code
        run: |
          npm run lint
          npm run copy:paste:detector
      - name: Compile source code
        run: npm run compile
      - name: Run unit tests
        run: npm run test:unit:coverage
      - name: Run integration tests
        run: npm run test:integration
        env:
          REDIS_HOST: redis
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: target/coverage/clover.xml
